language: python

python:
#    - "3.5"
    - "3.6"
    - "3.7"

install:
    - echo "install"
    - python setup.py develop

script:
    - nosetests -v --nologcapture --with-coverage --cover-package=criticalityMaps

after_success:
    coveralls
