name: docbuild
channels:
        - defaults
        - conda-forge
dependencies:
            - python=3.7
            - wntr
            - numpy
            - scipy
            - networkx
            - pandas
            - matplotlib
            - utm
            - pyyaml
            - jinja2
            - sphinx
            - numpydoc
